My new branch
YuhanLi1998/community-notes-factchecking pull request #1
Opened 2024-09-09 20:02 UTC by YuhanLi1998

2024-09-12 00:50 UTC, yang3kc requested changes
Thank you for putting this together! I think the script looks great.

I left some comments and recommendations, mainly regarding documentation and formatting.

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +from langdetect import detect, DetectorFactory
Given that we're using third-party packages, I think we need to add a requirements.txt file, see issue at https://github.com/YuhanLi1998/community-notes-factchecking/issues/3

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +    notes = pd.read_csv('/Users/liyuhan/Community_Notes/replication/notes-00000.tsv', sep='\t')
Hardcoding the file paths will make it impossible for others to rerun this code. I suggest making the data folder a variable that can be passed into the script.

For example:

```py
import sys
import os

data_path = sys.argv[1]
notes_path = os.path.join(data_path, 'notes-00000.tsv')
rating_files = ['ratings-00000.tsv', 'ratings-00001.tsv', 'ratings-00002.tsv', 'ratings-00003.tsv', 'ratings-00004.tsv']
ratings_path = [os.path.join(data_path, file) for file in rating_files]
```

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +        '/Users/liyuhan/Community_Notes/replication/ratings-00004.tsv'
See comment above.

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +import pandas as pd
Please add a docstring to this file that describes the input and output, as well as the basic logic of the script, to help others understand.

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +import pandas as pd
Something like:

```py
"""
This script preprocesses community notes data by filtering out non-English notes
and combining user ratings from multiple TSV files.

Functions:
    detect_english(text):
        Detects if a given text is in English.

        Parameters:
            text (str): The text to be checked for English language.

        Returns:
            bool: True if the text is in English, False otherwise.

Main Function:
    main():
        - Reads the notes data from a TSV file.
        - Filters the notes to keep only English summaries.
        - Reads and combines user ratings from multiple TSV files.
        - Displays the number of English notes and unique note IDs with user ratings.

        Input:
            TSV files containing notes and user ratings.

        Output:
            Prints the number of English notes and the number of unique note IDs with user ratings.
"""
```

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +import pandas as pd
For other scripts, please add docstring as well.

2024-09-12 00:50 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +    eng_notes.to_csv('/Users/liyuhan/Community_Notes/replication/English_notes_with_helpfulnesslevel.csv', index=False)
Again, please parameterize the output file path.

2024-09-14 18:37 UTC, YuhanLi1998 commented on scripts/load_data_preprocessing.py
> +import pandas as pd
I've added a docstring at the top of this script. Also, I supplemented the official web links to download these datasets (notes & user ratings) in the docstring.

2024-09-14 18:38 UTC, YuhanLi1998 commented on scripts/load_data_preprocessing.py
> +    notes = pd.read_csv('/Users/liyuhan/Community_Notes/replication/notes-00000.tsv', sep='\t')
Resolved this problem. People can define the dataset path in the terminal and run the scripts directly.

2024-09-14 18:39 UTC, YuhanLi1998 commented on scripts/load_data_preprocessing.py
> +        '/Users/liyuhan/Community_Notes/replication/ratings-00004.tsv'
Addressed this issue!

2024-09-14 18:40 UTC, YuhanLi1998 commented on scripts/load_data_preprocessing.py
> +from langdetect import detect, DetectorFactory
Have created a requirements.txt file containing required packages. Since the following scripts still require some new packages, I will keep updating the requirements.txt.

2024-09-14 18:41 UTC, YuhanLi1998 commented on scripts/load_data_preprocessing.py
> +    eng_notes.to_csv('/Users/liyuhan/Community_Notes/replication/English_notes_with_helpfulnesslevel.csv', index=False)
The way of saving the output file is also defined as above.

2024-09-15 14:43 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +from langdetect import detect, DetectorFactory
Thanks!

2024-09-15 14:43 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +    notes = pd.read_csv('/Users/liyuhan/Community_Notes/replication/notes-00000.tsv', sep='\t')
Great!

2024-09-15 14:44 UTC, yang3kc commented on scripts/load_data_preprocessing.py
> +import pandas as pd
Fantastic!

2024-09-15 15:10 UTC, yang3kc approved these changes
Thank you for making all the changes! This looks great, and I will merge it soon. Congratulations on your first successful pull request!

2024-09-15 15:10 UTC, merged