Add Python script for pronouns, readability, and subjectivity analysis
YuhanLi1998/community-notes-factchecking pull request #5
Opened 2024-09-30 05:32 UTC by YuhanLi1998

Hi Kaicheng and Jiaxin, this is the script for running pronouns, readability, and subjectivity analysis. I added some docstrings on the top of the script. Also, the way of inserting input data is in line with the prior way that Kaicheng mentioned before. Please leave any comment here if any revision is needed! Thank you so much.

2024-10-01 00:11 UTC, yang3kc requested changes
Thank you for creating this pull request. The added docstrings greatly enhance the readability of the code!

I have left some comments; please try to address them. I also have some additional general suggestions regarding the entire script.

1. Assume the script conflicts with the existing file in the main branch. You will need to resolve the conflict before we can merge. For the future, if you want to avoid such conflicts, be sure to check out your new branch from the main branch each time. And try not to work on branches that are behind the main branch.
2. It seems this script is trying to do three things simultaneously. Although you don't have to this time, a general principle is to keep each script atomic, meaning they should each perform only one function. For example, in this case, you can divide the script into three parts. This will make the code much easier to organize and read. And if you need to change one part, you don't have to rerun the other parts.
3. Please add a README file in this folder describing the entire pipeline. Include instructions on the order of execution for the various scripts, and describe their input and output.

2024-10-01 00:11 UTC, yang3kc commented on scripts/pronouns_subjectivity_readability.py
> +    notes_path = os.path.join(data_path, 'onlyEnglish-notes-LIWC-withhelpfulnesslevel.csv')
I don't think I have seen the code that was used to generate this file: `'onlyEnglish-notes-LIWC-withhelpfulnesslevel.csv'`. Could you point me to it?

If it's missing, I think it's better to add that script first because downstream analysis depends on it.

2024-10-06 18:53 UTC, YuhanLi1998 commented on scripts/pronouns_subjectivity_readability.py
> +    notes_path = os.path.join(data_path, 'onlyEnglish-notes-LIWC-withhelpfulnesslevel.csv')
Hi Kaicheng, I uploaded the script for producing the file named "LIWC-English-notes-withhelpfulnesslevel.csv", please refer to the new pull request named "Add script of running liwc analysis."

2024-10-06 18:54 UTC, YuhanLi1998 commented on scripts/pronouns_subjectivity_readability.py
>  import nltk
I have sent a new pull request to update the requirements.txt file.

2024-10-06 23:32 UTC, YuhanLi1998 commented on scripts/pronouns_subjectivity_readability.py
> +    subjectivity_lexicon_path = os.path.join(data_path, 'subjectivity_clues_hltemnlp05/subjclueslen1-HLTEMNLP05.tff')
Hi Kaicheng, I add some instructions about the Subjectivity Lexicon in the docstring at the top of the calculating_subjectivity.py script. I think this way could make readers easier to understand the dictionary when they read the script, rather than costing more time to look at the README file further.

2024-10-06 23:33 UTC, YuhanLi1998 commented on scripts/pronouns_subjectivity_readability.py
> +    data = pd.read_csv(notes_path, low_memory=False)
I add "low_memory=False" in every separate script file.

2024-10-09 21:09 UTC, closed without merging